// GENERATED by tools/generate_bindings.py - do not hand-edit.
// Edit CONTROLS in that script and re-run it instead.
#pragma once

#include <array>
#include <string_view>

// Every control this mod can bind. `event` is the RE::ControlMap user event a bind
// delivers, and the three ini keys hold the player's button, modifier, and blocking choice.
namespace GKK::Controls
{
	struct Control
	{
		std::string_view event;
		std::string_view label;        // player-facing, for diagnostics
		std::string_view iniSection;
		std::string_view buttonKey;
		std::string_view modifierKey;
		std::string_view blockKey;
	};

	inline constexpr std::array<Control, 15> kAll{ {
		{ "Quicksave"sv, "Quick Save"sv, "Saving"sv, "iQuicksaveGamepadButton"sv, "iQuicksaveGamepadModifier"sv, "iQuicksaveBlockMode"sv },
		{ "Quickload"sv, "Quick Load"sv, "Saving"sv, "iQuickloadGamepadButton"sv, "iQuickloadGamepadModifier"sv, "iQuickloadBlockMode"sv },
		{ "Quickkeys"sv, "Favorites"sv, "PipboyMenus"sv, "iQuickkeysGamepadButton"sv, "iQuickkeysGamepadModifier"sv, "iQuickkeysBlockMode"sv },
		{ "QuickStats"sv, "Stats"sv, "PipboyMenus"sv, "iQuickStatsGamepadButton"sv, "iQuickStatsGamepadModifier"sv, "iQuickStatsBlockMode"sv },
		{ "QuickInventory"sv, "Inventory"sv, "PipboyMenus"sv, "iQuickInventoryGamepadButton"sv, "iQuickInventoryGamepadModifier"sv, "iQuickInventoryBlockMode"sv },
		{ "QuickData"sv, "Data"sv, "PipboyMenus"sv, "iQuickDataGamepadButton"sv, "iQuickDataGamepadModifier"sv, "iQuickDataBlockMode"sv },
		{ "QuickMap"sv, "Map"sv, "PipboyMenus"sv, "iQuickMapGamepadButton"sv, "iQuickMapGamepadModifier"sv, "iQuickMapBlockMode"sv },
		{ "QuickRadio"sv, "Radio"sv, "PipboyMenus"sv, "iQuickRadioGamepadButton"sv, "iQuickRadioGamepadModifier"sv, "iQuickRadioBlockMode"sv },
		{ "AutoMove"sv, "Auto-Move"sv, "Movement"sv, "iAutoMoveGamepadButton"sv, "iAutoMoveGamepadModifier"sv, "iAutoMoveBlockMode"sv },
		{ "Run"sv, "Run"sv, "Movement"sv, "iRunGamepadButton"sv, "iRunGamepadModifier"sv, "iRunBlockMode"sv },
		{ "ToggleAlwaysRun"sv, "Always Run"sv, "Movement"sv, "iToggleAlwaysRunGamepadButton"sv, "iToggleAlwaysRunGamepadModifier"sv, "iToggleAlwaysRunBlockMode"sv },
		{ "Forward"sv, "Forward"sv, "Movement"sv, "iForwardGamepadButton"sv, "iForwardGamepadModifier"sv, "iForwardBlockMode"sv },
		{ "Back"sv, "Back"sv, "Movement"sv, "iBackGamepadButton"sv, "iBackGamepadModifier"sv, "iBackBlockMode"sv },
		{ "StrafeLeft"sv, "Strafe Left"sv, "Movement"sv, "iStrafeLeftGamepadButton"sv, "iStrafeLeftGamepadModifier"sv, "iStrafeLeftBlockMode"sv },
		{ "StrafeRight"sv, "Strafe Right"sv, "Movement"sv, "iStrafeRightGamepadButton"sv, "iStrafeRightGamepadModifier"sv, "iStrafeRightBlockMode"sv },
	} };
}
