// GENERATED by tools/generate_bindings.py - do not hand-edit.
// Edit BINDINGS in that script and re-run it instead.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

// Vanilla defaults for every action this mod can bind or unbind, from the shipped
// CustomControlMap.txt. kUnbound means the action has no default on that device at
// all, which is not the same as "currently unbound", and is the first of
// ControlMapService's two applicability guards. The second is the live `remappable`
// flag, read from the engine at call time because any mod can ship its own
// ControlMap_Custom.txt.
namespace UnbindAny::Bindings
{
	inline constexpr std::int32_t kUnbound = static_cast<std::int32_t>(RE::kInvalidMappedKey);

	struct Binding
	{
		std::string_view eventID;         // ControlMap UserEvent name
		std::string_view displayName;     // player-facing, for notifications and status lines
		std::string_view labelKey;        // translation key for displayName, the MCM page's own
		std::int32_t     keyboardDefault;
		std::int32_t     mouseDefault;
		std::int32_t     gamepadDefault;
		std::string_view displayKeyboard;  // vanilla default, for status text
		std::string_view displayGamepad;

		// True for entries the engine refuses to remap (remappable=0) and never persists. They go
		// straight into inputKey, are gone on every launch, and have to be re-applied each pass, so
		// the SETTING is the source of truth for them. Everything else persists in
		// ControlMap_Custom.txt, where the engine is.
		bool             inMemory;
	};

	inline constexpr std::array<Binding, 31> kAll{ {
		{ "Forward"sv, "Move Forward"sv, "$UC_KBM_Forward_Text"sv, 87, kUnbound, kUnbound, "W"sv, ""sv, false },
		{ "Back"sv, "Move Backward"sv, "$UC_KBM_Back_Text"sv, 83, kUnbound, kUnbound, "S"sv, ""sv, false },
		{ "StrafeLeft"sv, "Strafe Left"sv, "$UC_KBM_StrafeLeft_Text"sv, 65, kUnbound, kUnbound, "A"sv, ""sv, false },
		{ "StrafeRight"sv, "Strafe Right"sv, "$UC_KBM_StrafeRight_Text"sv, 68, kUnbound, kUnbound, "D"sv, ""sv, false },
		{ "Jump"sv, "Jump"sv, "$UC_KBM_Jump_Text"sv, 32, kUnbound, 32768, "Space"sv, "Y Button"sv, false },
		{ "Sprint"sv, "Sprint"sv, "$UC_KBM_Sprint_Text"sv, 160, kUnbound, 64, "Left Shift"sv, "Left Stick Click (L3)"sv, false },
		{ "Sneak"sv, "Sneak"sv, "$UC_KBM_Sneak_Text"sv, 162, kUnbound, 128, "Left Ctrl"sv, "Right Stick Click (R3)"sv, false },
		{ "Run"sv, "Run (Hold-to-Run Modifier)"sv, "$UC_KBM_Run_Text"sv, 67, kUnbound, kUnbound, "C"sv, ""sv, false },
		{ "ToggleAlwaysRun"sv, "Always Run (Toggle)"sv, "$UC_KBM_ToggleAlwaysRun_Text"sv, 20, kUnbound, kUnbound, "Caps Lock"sv, ""sv, false },
		{ "AutoMove"sv, "Auto-Move"sv, "$UC_KBM_AutoMove_Text"sv, 88, kUnbound, kUnbound, "X"sv, ""sv, false },
		{ "PrimaryAttack"sv, "Attack / Fire"sv, "$UC_KBM_PrimaryAttack_Text"sv, kUnbound, 0, 10, "Mouse: Left Click"sv, "Right Trigger (RT)"sv, false },
		{ "SecondaryAttack"sv, "Aim"sv, "$UC_KBM_SecondaryAttack_Text"sv, kUnbound, 1, 9, "Mouse: Right Click"sv, "Left Trigger (LT)"sv, false },
		{ "Melee"sv, "Melee / Throw Grenade"sv, "$UC_KBM_Melee_Text"sv, 164, kUnbound, 512, "Left Alt"sv, "Right Bumper (RB)"sv, false },
		{ "VATS"sv, "V.A.T.S."sv, "$UC_KBM_VATS_Text"sv, 81, kUnbound, 256, "Q"sv, "Left Bumper (LB)"sv, false },
		{ "Activate"sv, "Activate"sv, "$UC_KBM_Activate_Text"sv, 69, kUnbound, 4096, "E"sv, "A Button"sv, false },
		{ "ReadyWeapon"sv, "Reload / Holster Weapon"sv, "$UC_KBM_ReadyWeapon_Text"sv, 82, kUnbound, 16384, "R"sv, "X Button"sv, false },
		{ "TogglePOV"sv, "Toggle Camera View (1st/3rd Person)"sv, "$UC_KBM_TogglePOV_Text"sv, 86, 2, 32, "V / Mouse: Middle Click"sv, "Back / View Button"sv, false },
		{ "Pipboy"sv, "Pip-Boy"sv, "$UC_KBM_Pipboy_Text"sv, 9, kUnbound, 8192, "Tab"sv, "B Button"sv, false },
		{ "Quickkeys"sv, "Favorites Menu"sv, "$UC_KBM_Quickkeys_Text"sv, 70, kUnbound, kUnbound, "F"sv, ""sv, false },
		{ "Quicksave"sv, "Quick Save"sv, "$UC_KBM_Quicksave_Text"sv, 116, kUnbound, kUnbound, "F5"sv, ""sv, false },
		{ "Quickload"sv, "Quick Load"sv, "$UC_KBM_Quickload_Text"sv, 120, kUnbound, kUnbound, "F9"sv, ""sv, false },
		{ "Pause"sv, "Pause Menu"sv, "$UC_KBM_Pause_Text"sv, 27, kUnbound, 16, "Esc"sv, "Start / Menu Button"sv, false },
		{ "QuickStats"sv, "Stats (Quick Access)"sv, "$UC_KBM_QuickStats_Text"sv, 75, kUnbound, kUnbound, "K"sv, ""sv, false },
		{ "QuickInventory"sv, "Inventory (Quick Access)"sv, "$UC_KBM_QuickInventory_Text"sv, 73, kUnbound, kUnbound, "I"sv, ""sv, false },
		{ "QuickData"sv, "Data / Quests (Quick Access)"sv, "$UC_KBM_QuickData_Text"sv, 74, kUnbound, kUnbound, "J"sv, ""sv, false },
		{ "QuickMap"sv, "Map (Quick Access)"sv, "$UC_KBM_QuickMap_Text"sv, 77, kUnbound, kUnbound, "M"sv, ""sv, false },
		{ "QuickRadio"sv, "Radio (Quick Access)"sv, "$UC_KBM_QuickRadio_Text"sv, 79, kUnbound, kUnbound, "O"sv, ""sv, false },
		{ "QuickkeyUp"sv, "Quick Slot Up"sv, "$UC_GP_QuickSlotUp_Text"sv, kUnbound, kUnbound, 1, ""sv, "D-Pad Up"sv, true },
		{ "QuickkeyDown"sv, "Quick Slot Down"sv, "$UC_GP_QuickSlotDown_Text"sv, kUnbound, kUnbound, 2, ""sv, "D-Pad Down"sv, true },
		{ "QuickkeyLeft"sv, "Quick Slot Left"sv, "$UC_GP_QuickSlotLeft_Text"sv, kUnbound, kUnbound, 4, ""sv, "D-Pad Left"sv, true },
		{ "QuickkeyRight"sv, "Quick Slot Right"sv, "$UC_GP_QuickSlotRight_Text"sv, kUnbound, kUnbound, 8, ""sv, "D-Pad Right"sv, true },
	} };

	[[nodiscard]] inline const Binding* Find(std::string_view a_eventID)
	{
		for (const auto& b : kAll) {
			if (b.eventID == a_eventID) {
				return &b;
			}
		}
		return nullptr;
	}

	// The MCM setting and translation-key stem for an event. Identical to the eventID except
	// for the four Quickkey directions, which MCM names QuickSlot*.
	[[nodiscard]] inline std::string_view SettingStem(std::string_view a_event)
	{
		if (a_event == "QuickkeyUp"sv) {
			return "QuickSlotUp"sv;
		}
		if (a_event == "QuickkeyDown"sv) {
			return "QuickSlotDown"sv;
		}
		if (a_event == "QuickkeyLeft"sv) {
			return "QuickSlotLeft"sv;
		}
		if (a_event == "QuickkeyRight"sv) {
			return "QuickSlotRight"sv;
		}
		return a_event;
	}
}
