// GENERATED by tools/generate_bindings.py - do not hand-edit.
// Edit BINDINGS in that script and re-run it instead.
#pragma once

#include <cstdint>
#include <windows.h>

namespace UnbindAny::Settings
{
	// MCM writes to Data\MCM\Settings\WIO-ControlUnbinder.ini on every control change. This
	// plugin never writes that file; it only reads it on demand via GetPrivateProfileStringA.
	constexpr auto kMCMSettingsPath = R"(Data\MCM\Settings\WIO-ControlUnbinder.ini)";

	constexpr std::int32_t kUnbound = static_cast<std::int32_t>(RE::kInvalidMappedKey);

	// Accepts both 1/0 (what MCM writes) and true/false. a_default applies only when the key is
	// missing from the runtime Settings ini, the normal state for a control never touched: MCM
	// writes a key there only once the control is used, and never copies the shipped Config
	// defaults in. A toggle whose shipped default is ON must pass a_default="1".
	inline bool GetDesired(const char* a_section, const char* a_key, const char* a_default = "0")
	{
		return WIO::Ini::GetBool(a_section, a_key, WIO::Ini::ParseBool(a_default, false), kMCMSettingsPath);
	}

	// Gamepad in-memory defaults (raw XInput D-Pad bitmasks). RemapButton refuses these
	// entries (remappable=false in CustomControlMap.txt) - written directly instead.
	//
	// Only the in-memory entries carry a default here. Every other action's vanilla
	// defaults live in Bindings.h, which is what ControlMapService reads.
	constexpr std::int32_t kGP_QuickSlotUp_Default = 1;  // D-Pad Up
	constexpr std::int32_t kGP_QuickSlotDown_Default = 2;  // D-Pad Down
	constexpr std::int32_t kGP_QuickSlotLeft_Default = 4;  // D-Pad Left
	constexpr std::int32_t kGP_QuickSlotRight_Default = 8;  // D-Pad Right
}
